Italics added and bold improvised
Horizon733/certi-build pull request #3
Opened 2021-09-30 23:14 UTC by debajyotisarkarhome

Added options to italicize text, improvised the bold option too using font selection. By default it'll use a proprietary font, unless explicitly defined by the font-file-path tag.

2021-10-01 05:23 UTC, Horizon733 commented
> Added options to italicize text, improvised the bold option too using font selection. By default it'll use a proprietary font, unless explicitly defined by the font-file-path tag.

Please add issue number so it is connected

2021-10-01 06:17 UTC, debajyotisarkarhome commented
Successfully Linked with issue #2

2021-10-01 09:53 UTC, Horizon733 commented
@debajyotisarkarhome I will be testing your branch locally and then will move forward!

2021-10-02 04:49 UTC, debajyotisarkarhome commented
Sure!

2021-10-02 06:36 UTC, Horizon733 commented
Make sure to remove all unnecessary font files before committing the code. E.g inside fonts there are a lot of font files that aren't needed we just need bold, regular, and italic. 

So, make sure to add all the changes and make sure to rebase your branch and keep one commit and not more than that.

2021-10-02 06:40 UTC, Horizon733 requested changes

2021-10-02 06:40 UTC, Horizon733 commented on certi_builder/builder.py
> +            drawImage.text(location, name,(0,0,0), font=font)
is there any particular reason, you haven't used text color for names? since that is required for generating certificates

2021-10-02 06:40 UTC, Horizon733 commented on certi_builder/builder.py
> +    font_italic=ImageFont.truetype(os.getcwd()+"/fonts/Roboto-Italic.ttf", font_size)
make sure to use black for formating code before pushing here,

2021-10-08 16:06 UTC, closed without merging